import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthSessionProvider from "@/components/AuthSessionProvider";
import ConditionalAppChrome from "@/components/ConditionalAppChrome";
import { MobileNavProvider } from "@/components/MobileNavContext";
import { resolveBaseAudienceMode } from "@/lib/audienceMode";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Resolved here (server-side, before pathname is known) so the initial
  // HTML for the chip is already correct — see ConditionalAppChrome for
  // where the /advisors pathname override composes with this.
  const { mode: baseAudienceMode, switchable: audienceModeSwitchable } = await resolveBaseAudienceMode();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-hidden">
        <AuthSessionProvider>
          <MobileNavProvider>
            <ConditionalAppChrome baseAudienceMode={baseAudienceMode} audienceModeSwitchable={audienceModeSwitchable}>
              {children}
            </ConditionalAppChrome>
          </MobileNavProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
