"use client";

import { useEffect, useState } from "react";
import {
  AlertTriangle,
  BarChart3,
  Minus,
  TrendingDown,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";
import RevealOnScroll from "@/components/RevealOnScroll";
import StockLogo from "@/components/stocks/StockLogo";
import HowItWorksAccordion from "@/components/tools/HowItWorksAccordion";
import { cardClass } from "@/lib/cardStyles";
import type { SignalDataSnapshot, SignalDirection } from "@/lib/signals/types";

interface SignalEntry {
  ticker: string;
  companyName: string;
  available: boolean;
  direction?: SignalDirection;
  confidence?: number;
  rationale?: string;
  dataSnapshot?: SignalDataSnapshot;
  generatedAt?: string;
}

interface SignalsResponse {
  signals: SignalEntry[];
  lastGeneratedAt: string | null;
}

const DIRECTION_META: Record<SignalDirection, { label: string; Icon: LucideIcon; badgeClass: string; barClass: string }> = {
  bullish: { label: "Bullish", Icon: TrendingUp, badgeClass: "bg-green-400/10 text-green-500", barClass: "bg-green-500" },
  bearish: { label: "Bearish", Icon: TrendingDown, badgeClass: "bg-red-400/10 text-red-500", barClass: "bg-red-500" },
  neutral: { label: "Neutral", Icon: Minus, badgeClass: "bg-foreground/10 text-foreground/60", barClass: "bg-foreground/40" },
};

function formatMoney(value: number | null): string {
  return value === null ? "N/A" : `$${value.toFixed(2)}`;
}

function formatPercent(value: number | null): string {
  return value === null ? "N/A" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`;
}

// Prominent, persistent, non-dismissible — deliberately more visible than
// this app's usual plain-text disclaimer convention (see
// SimulatedTradingDisclaimer.tsx/ModelPortfolioDisclaimer.tsx's own
// "informational boilerplate, not a data caveat" reasoning for staying
// plain). AI-generated trade calls are a higher-stakes claim than "this
// is a simulation," so this one gets the app's established amber
// caution treatment instead.
function SignalsDisclaimer() {
  return (
    <div className="flex w-full items-start gap-3 rounded-lg border border-amber-400/30 bg-amber-400/5 p-4">
      <AlertTriangle size={20} className="mt-0.5 shrink-0 text-amber-500" />
      <p className="text-sm leading-relaxed text-foreground/80">
        <span className="font-semibold text-amber-500">Educational content only, not investment advice.</span>{" "}
        Every signal below is generated by an AI model from historical/public data and is not personalized to you
        or your holdings. Noble does not execute trades, place orders, or connect to any brokerage account — nothing
        on this page can buy or sell anything on your behalf.
      </p>
    </div>
  );
}

// Reused from lib/signals/gather.ts's own TrackerActivitySnapshot shape —
// insider (Form 4) and congressional (PTR) rows render identically here,
// just under different headings.
function ActivityList({ entries }: { entries: SignalDataSnapshot["insiderActivity"] }) {
  if (entries.length === 0) return <p className="text-foreground/40">None in the tracked window</p>;
  return (
    <ul className="flex flex-col gap-0.5">
      {entries.map((entry, i) => (
        <li key={i}>
          {entry.reportingPersonName ?? entry.entityName}: {entry.transactionType}
          {entry.reportedDate ? ` (${new Date(entry.reportedDate).toLocaleDateString("en-US", { month: "short", day: "numeric" })})` : ""}
        </li>
      ))}
    </ul>
  );
}

function DataBreakdown({ snapshot }: { snapshot: SignalDataSnapshot }) {
  const { technical, analystRating, priceTarget, earnings, news, insiderActivity, congressActivity } = snapshot;

  return (
    <HowItWorksAccordion label="Data used for this signal" icon={BarChart3} iconColorClass="text-indigo-400">
      <div className="grid grid-cols-2 gap-x-3 gap-y-1">
        <span>50-day SMA</span>
        <span className="text-right text-foreground">{formatMoney(technical.sma50)}</span>
        <span>200-day SMA</span>
        <span className="text-right text-foreground">{formatMoney(technical.sma200)}</span>
        <span>RSI (14)</span>
        <span className="text-right text-foreground">{technical.rsi14 !== null ? technical.rsi14.toFixed(1) : "N/A"}</span>
        <span>Volume trend</span>
        <span className="text-right text-foreground">{formatPercent(technical.volumeTrendPercent)}</span>
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">Analyst rating</p>
        <p>{analystRating ? `${analystRating.ratingLabel} (${analystRating.rating?.toFixed(2)}/5)` : "Not available"}</p>
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">Price target</p>
        <p>
          {priceTarget
            ? `Low ${formatMoney(priceTarget.low)} · Avg ${formatMoney(priceTarget.average)} · High ${formatMoney(priceTarget.high)}`
            : "Not available for this ticker"}
        </p>
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">Earnings</p>
        <p>{earnings?.nextEarningsDate ? `Next report: ${earnings.nextEarningsDate}` : "No upcoming date known"}</p>
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">News headlines considered ({news.length})</p>
        {news.length > 0 ? (
          <ul className="flex flex-col gap-0.5">
            {news.map((n, i) => (
              <li key={i} className="truncate">
                {n.title}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-foreground/40">None found</p>
        )}
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">Insider trading activity</p>
        <ActivityList entries={insiderActivity} />
      </div>

      <div className="border-t border-black/10 pt-2 dark:border-white/15">
        <p className="font-medium text-foreground">Congressional trading activity</p>
        <ActivityList entries={congressActivity} />
      </div>
    </HowItWorksAccordion>
  );
}

function SignalCard({ signal }: { signal: SignalEntry }) {
  if (!signal.available || !signal.direction || signal.confidence === undefined || !signal.rationale || !signal.dataSnapshot) {
    return (
      <div className={cardClass("neutral", { extra: "flex flex-col items-center gap-2 p-6 text-center" })}>
        <StockLogo symbol={signal.ticker} size={36} />
        <p className="font-semibold text-foreground">{signal.ticker}</p>
        <p className="text-xs text-foreground/50">{signal.companyName}</p>
        <p className="mt-1 text-xs text-foreground/40">Signal not yet generated</p>
      </div>
    );
  }

  const meta = DIRECTION_META[signal.direction];

  return (
    <div className={cardClass("neutral", { extra: "flex flex-col gap-3 p-4" })}>
      <div className="flex items-center gap-3">
        <StockLogo symbol={signal.ticker} size={36} />
        <div className="min-w-0 flex-1">
          <p className="font-semibold text-foreground">{signal.ticker}</p>
          <p className="truncate text-xs text-foreground/50">{signal.companyName}</p>
        </div>
        <span className={`inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${meta.badgeClass}`}>
          <meta.Icon size={13} />
          {meta.label}
        </span>
      </div>

      <div className="flex items-center gap-2">
        <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-foreground/10">
          <div className={`h-full rounded-full ${meta.barClass}`} style={{ width: `${signal.confidence}%` }} />
        </div>
        <span className="shrink-0 text-xs font-medium text-foreground/60">{signal.confidence}% confidence</span>
      </div>

      <p className="text-sm leading-relaxed text-foreground/70">{signal.rationale}</p>

      <DataBreakdown snapshot={signal.dataSnapshot} />
    </div>
  );
}

function formatGeneratedTimestamp(iso: string | null): string {
  if (!iso) return "Not yet generated";
  return new Date(iso).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short",
  });
}

export default function SignalsPage() {
  const [data, setData] = useState<SignalsResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const response = await fetch("/api/signals");
        const body = await response.json().catch(() => null);
        if (cancelled) return;
        if (!response.ok || !Array.isArray(body?.signals)) {
          setError("Failed to load signals");
          return;
        }
        setData(body);
      } catch {
        if (!cancelled) setError("Failed to load signals");
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main className="flex flex-1 flex-col items-center gap-6 p-8 pt-16">
      <div className="flex w-full max-w-5xl flex-col gap-6">
        <RevealOnScroll className="flex flex-col gap-1">
          <h1 className="text-3xl font-bold text-foreground">AI Trade Signals</h1>
          <p className="text-sm text-foreground/60">
            Daily, AI-generated directional signals for a fixed watchlist of major tickers — built from real
            technical indicators, analyst data, earnings, news, and insider/congressional trading activity.
          </p>
        </RevealOnScroll>

        <RevealOnScroll>
          <SignalsDisclaimer />
        </RevealOnScroll>

        {error && <p className="text-sm text-red-500">{error}</p>}

        {data && (
          <p className="text-xs text-foreground/50">
            Signals last generated: <span className="font-medium text-foreground/70">{formatGeneratedTimestamp(data.lastGeneratedAt)}</span>
          </p>
        )}

        {!data && !error && (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="h-48 w-full animate-pulse rounded-lg bg-foreground/10" />
            ))}
          </div>
        )}

        {data && (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {data.signals.map((signal) => (
              <SignalCard key={signal.ticker} signal={signal} />
            ))}
          </div>
        )}
      </div>
    </main>
  );
}
